package com.playtranslate.language

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Test

/**
 * Proves [MaximalMatchThaiSegmenter] reproduces PyThaiNLP 5.3.4 `newmm`
 * byte-for-byte on real Thai sentences — the "agreement vs newmm" validation, at
 * 100% on a fixture. Fixtures are generated by `scripts/eval_thai_segmenter.py`:
 *  - `newmm_words.txt`: the DAG-complete wordlist (every PyThaiNLP word that is a
 *    prefix at any position in the fixture sentences), so our trie yields a match
 *    DAG identical to PyThaiNLP's.
 *  - `newmm_fixture.tsv`: `text <tab> gold-token…`, gold from PyThaiNLP newmm over
 *    that wordlist.
 *
 * A divergence means our port deviates from upstream — regenerate the fixture and
 * investigate (likely the prefix order, BFS path choice, or graph cutoff).
 */
class ThaiNewmmFidelityTest {

    private fun resource(path: String): String {
        val stream = javaClass.getResourceAsStream(path)
        assertNotNull("missing test resource $path", stream)
        return stream!!.bufferedReader().use { it.readText() }
    }

    @Test fun `port reproduces PyThaiNLP newmm exactly`() {
        val words = resource("/thai/newmm_words.txt")
            .lineSequence().map { it.trim() }.filter { it.isNotEmpty() }.toList()
        val seg = MaximalMatchThaiSegmenter(ThaiWordTrie.of(words))

        val lines = resource("/thai/newmm_fixture.tsv")
            .lineSequence().filter { it.isNotEmpty() }.toList()
        assertEquals("fixture sentence count", 22, lines.size)

        for (line in lines) {
            val parts = line.split('\t')
            val text = parts[0]
            val gold = parts.drop(1)
            assertEquals("newmm segmentation of '$text'", gold, seg.segment(text))
        }
    }
}
