package com.playtranslate.ui

/**
 * Builds [CardOutputs] from the sheet-side state. The send-time
 * dispatcher passes the resulting struct to
 * [AnkiCardTypeMapper.assembleNote] alongside the user's saved field
 * mapping; each [ContentSource] picks one string from the outputs.
 *
 * Word-card definition HTML is supplied by the caller (the word sheet)
 * because it depends on per-card curation state (`removedSenses`,
 * `removedExamples`, `removedTatoebaIdx`). Sentence-card definition is
 * derived inline from the first highlighted word's `meaning`.
 */
object AnkiCardOutputBuilder {

    /**
     * Wraps an AnkiDroid-side media filename in the `<img>` markup
     * mining templates expect in their Picture/Screenshot field.
     *
     * Why wrap here and not pass the bare filename: Lapis, JPMN,
     * Migaku, and Anki Basic all render their picture-slot field via a
     * literal `{{Picture}}` (or `{{Screenshot}}`) mustache — they don't
     * wrap the field's contents in `<img>` themselves. The Yomitan
     * ecosystem convention is for the field to ALREADY contain `<img>`
     * markup, typically generated by Yomitan's `{screenshot-html}`
     * marker. The legacy v004 path wraps internally (see
     * SentenceAnkiHtmlBuilder.buildBackHtml), so this is the structured
     * path's parallel.
     *
     * `max-width:100%` keeps the image from busting out of narrow card
     * widths on mobile AnkiDroid. We deliberately don't ship
     * border-radius / margins — those are template-styling concerns
     * the user's CSS should own.
     */
    private fun pictureHtml(imageFilename: String?): String =
        if (imageFilename.isNullOrEmpty()) ""
        else "<img src=\"$imageFilename\" style=\"max-width:100%;\">"

    /**
     * Builds outputs from a sentence sheet's current state. The caller
     * may supply pre-rendered [examplesHtml] (Tatoeba pairs for the
     * highlighted word) — usually available only when the send is
     * routed through [WordAnkiReviewSheet], which carries the
     * surrounding word-lookup context. Sentence-only flows
     * ([AnkiReviewBottomSheet]) pass empty.
     */
    fun forSentence(
        cardData: SentenceAnkiContentFragment.CardData,
        imageFilename: String?,
        examplesHtml: String = "",
    ): CardOutputs {
        val firstHighlighted = cardData.words.firstOrNull {
            it.word in cardData.selectedWords
        }
        // EXPRESSION: highlighted word's headword folded with its
        // dict-reading into Anki-native furigana brackets when
        // applicable (JA). Falls back to the whole sentence as plain
        // text when nothing is highlighted — the field must be
        // non-empty in case a model uses sortf=0 and EXPRESSION lands
        // at the sort slot.
        val expression = firstHighlighted?.let {
            SentenceAnkiHtmlBuilder.buildExpressionFurigana(
                word = it.word, reading = it.reading,
                sourceLangId = cardData.sourceLangId,
            )
        } ?: cardData.source.replace(Regex("[\\n\\r]+"), " ").trim()
        val reading = firstHighlighted?.reading.orEmpty()
        // DEFINITION: empty when nothing's highlighted. assembleNote's
        // sentence-mode fold (not yet implemented for this flow; see
        // plan §3 — left explicit "" so the WORDS_TABLE is what a user
        // would map their main definition field to instead).
        val definition = firstHighlighted?.meaning?.let { m ->
            m.lines().filter { it.isNotBlank() }
                .joinToString("<br>") { it.trimStart() }
        }.orEmpty()
        val frequency = firstHighlighted?.let {
            SentenceAnkiHtmlBuilder.starsString(it.freqScore)
        }.orEmpty()
        // SENTENCE always carries Anki-native furigana brackets — see
        // SentenceAnkiHtmlBuilder.buildSentenceFurigana. Templates with
        // a `{{furigana:Sentence}}` filter render ruby; templates that
        // bind `{{Sentence}}` bare show literal brackets (accepted
        // tradeoff for picker simplicity, one SENTENCE source).
        val sentenceHtml = SentenceAnkiHtmlBuilder.buildSentenceFurigana(
            text = cardData.source,
            sourceLangId = cardData.sourceLangId,
        )
        val translationHtml = cardData.target.replace(Regex("[\\n\\r]+"), "<br>")
        val sortedWords = if (cardData.selectedWords.isNotEmpty()) {
            cardData.words.sortedByDescending { it.word in cardData.selectedWords }
        } else cardData.words
        val wordsHtml = SentenceAnkiHtmlBuilder.buildWordsHtmlWith(
            sortedWords,
            cardData.selectedWords,
            styler = inlineStyler,
        )
        return CardOutputs(
            expression = expression,
            reading = reading,
            sentence = sentenceHtml,
            sentenceTranslation = translationHtml,
            picture = pictureHtml(imageFilename),
            definition = definition,
            examples = examplesHtml,
            frequency = frequency,
            partOfSpeech = "",
            wordsTable = wordsHtml,
            // Flag values for sentence-mode sends:
            //  - SENTENCE_CARD_FLAG always fires (Lapis/JPMN signal).
            //  - TARGETED_SENTENCE_CARD_FLAG fires only when there's a
            //    bolded word to target (JPMN's IsTargetedSentenceCard
            //    requires a bolded word in the Sentence field, which
            //    wrapHighlighted only produces with selectedWords).
            //  - VOCABULARY_CARD_FLAG stays empty — sentence sends are
            //    not vocab-variant cards.
            //  - ALWAYS_ON_MARKER fires for users who manually mapped a
            //    flag field to always-on.
            vocabularyCardFlag = "",
            sentenceCardFlag = "x",
            targetedSentenceCardFlag = if (cardData.selectedWords.isNotEmpty()) "x" else "",
            alwaysOnMarker = "x",
        )
    }

    /**
     * Builds outputs from a word-sheet send. [definitionHtml] is the
     * caller's pre-rendered Definition HTML (built via
     * `WordAnkiReviewSheet.buildWordDefinitionHtml(inlineStyler)`)
     * because it depends on the sheet's curation state. Same for
     * [examplesHtml] (Tatoeba pairs, honoring `removedTatoebaIdx`).
     */
    fun forWord(
        word: String,
        reading: String,
        pos: String,
        definitionHtml: String,
        freqScore: Int,
        imageFilename: String?,
        examplesHtml: String = "",
        sourceLangId: com.playtranslate.language.SourceLangId =
            com.playtranslate.language.SourceLangId.JA,
    ): CardOutputs = CardOutputs(
        // EXPRESSION: per-kanji furigana brackets so templates with a
        // `{{furigana:Expression}}` (or equivalent) filter render
        // ruby. Falls through to the bare word for non-JA langs.
        expression = SentenceAnkiHtmlBuilder.buildExpressionFurigana(
            word = word, reading = reading, sourceLangId = sourceLangId,
        ),
        reading = reading,
        sentence = "",
        sentenceTranslation = "",
        picture = pictureHtml(imageFilename),
        definition = definitionHtml,
        examples = examplesHtml,
        frequency = SentenceAnkiHtmlBuilder.starsString(freqScore),
        partOfSpeech = pos,
        wordsTable = "",
        // Flag values for word-mode sends: VOCABULARY_CARD_FLAG fires
        // (Migaku/Lapis vocab-variant signal); sentence flags stay
        // empty since word cards aren't sentence-variant. ALWAYS_ON
        // fires for manually-mapped always-on flag fields.
        vocabularyCardFlag = "x",
        sentenceCardFlag = "",
        targetedSentenceCardFlag = "",
        alwaysOnMarker = "x",
    )

}
