package com.playtranslate.ui

/**
 * Builds [CardOutputs] from the sheet-side state. The send-time
 * dispatcher passes the resulting struct to
 * [AnkiCardTypeMapper.assembleNote] alongside the user's saved field
 * mapping; each [ContentSource] picks one string from the outputs.
 *
 * Word-card definition HTML is supplied by the caller (the word sheet)
 * because it depends on per-card curation state (`removedSenses`,
 * `removedExamples`, `removedTatoebaIdx`). Sentence-card definition is
 * derived inline from the first highlighted word's `meaning`.
 */
object AnkiCardOutputBuilder {

    /**
     * Wraps an AnkiDroid-side media filename in the `<img>` markup
     * mining templates expect in their Picture/Screenshot field.
     *
     * Why wrap here and not pass the bare filename: Lapis, JPMN,
     * Migaku, and Anki Basic all render their picture-slot field via a
     * literal `{{Picture}}` (or `{{Screenshot}}`) mustache — they don't
     * wrap the field's contents in `<img>` themselves. The Yomitan
     * ecosystem convention is for the field to ALREADY contain `<img>`
     * markup, typically generated by Yomitan's `{screenshot-html}`
     * marker. The legacy v004 path wraps internally (see
     * SentenceAnkiHtmlBuilder.buildBackHtml), so this is the structured
     * path's parallel.
     *
     * `max-width:100%` keeps the image from busting out of narrow card
     * widths on mobile AnkiDroid. We deliberately don't ship
     * border-radius / margins — those are template-styling concerns
     * the user's CSS should own.
     */
    private fun pictureHtml(imageFilename: String?): String =
        if (imageFilename.isNullOrEmpty()) ""
        else "<img src=\"$imageFilename\" style=\"max-width:100%;\">"

    /**
     * Builds outputs from a sentence sheet's current state. The caller
     * may supply pre-rendered [examplesHtml] (Tatoeba pairs for the
     * highlighted word) — usually available only when the send is
     * routed through [WordAnkiReviewSheet], which carries the
     * surrounding word-lookup context. Sentence-only flows
     * ([AnkiReviewBottomSheet]) pass empty.
     */
    fun forSentence(
        cardData: SentenceAnkiContentFragment.CardData,
        imageFilename: String?,
        examplesHtml: String = "",
    ): CardOutputs {
        val firstHighlighted = cardData.words.firstOrNull {
            it.word in cardData.selectedWords
        }
        // EXPRESSION: prefer the first highlighted word; fall back to the
        // whole sentence so the field is non-empty (matters when a model
        // uses sortf=0 and EXPRESSION lands at the sort slot).
        val expression = firstHighlighted?.word
            ?: cardData.source.replace(Regex("[\\n\\r]+"), " ").trim()
        val reading = firstHighlighted?.reading.orEmpty()
        // DEFINITION: empty when nothing's highlighted. assembleNote's
        // sentence-mode fold (not yet implemented for this flow; see
        // plan §3 — left explicit "" so the WORDS_TABLE is what a user
        // would map their main definition field to instead).
        val definition = firstHighlighted?.meaning?.let { m ->
            m.lines().filter { it.isNotBlank() }
                .joinToString("<br>") { it.trimStart() }
        }.orEmpty()
        val frequency = firstHighlighted?.let {
            SentenceAnkiHtmlBuilder.starsString(it.freqScore)
        }.orEmpty()
        val sentenceHtml = wrapHighlighted(
            text = cardData.source,
            highlighted = cardData.selectedWords,
            words = cardData.words,
        )
        val translationHtml = cardData.target.replace(Regex("[\\n\\r]+"), "<br>")
        val sortedWords = if (cardData.selectedWords.isNotEmpty()) {
            cardData.words.sortedByDescending { it.word in cardData.selectedWords }
        } else cardData.words
        val wordsHtml = SentenceAnkiHtmlBuilder.buildWordsHtmlWith(
            sortedWords,
            cardData.selectedWords,
            styler = inlineStyler,
        )
        return CardOutputs(
            expression = expression,
            reading = reading,
            sentence = sentenceHtml,
            sentenceTranslation = translationHtml,
            picture = pictureHtml(imageFilename),
            definition = definition,
            examples = examplesHtml,
            frequency = frequency,
            partOfSpeech = "",
            wordsTable = wordsHtml,
            // Flag values for sentence-mode sends:
            //  - SENTENCE_CARD_FLAG always fires (Lapis/JPMN signal).
            //  - TARGETED_SENTENCE_CARD_FLAG fires only when there's a
            //    bolded word to target (JPMN's IsTargetedSentenceCard
            //    requires a bolded word in the Sentence field, which
            //    wrapHighlighted only produces with selectedWords).
            //  - VOCABULARY_CARD_FLAG stays empty — sentence sends are
            //    not vocab-variant cards.
            //  - ALWAYS_ON_MARKER fires for users who manually mapped a
            //    flag field to always-on.
            vocabularyCardFlag = "",
            sentenceCardFlag = "x",
            targetedSentenceCardFlag = if (cardData.selectedWords.isNotEmpty()) "x" else "",
            alwaysOnMarker = "x",
        )
    }

    /**
     * Builds outputs from a word-sheet send. [definitionHtml] is the
     * caller's pre-rendered Definition HTML (built via
     * `WordAnkiReviewSheet.buildWordDefinitionHtml(inlineStyler)`)
     * because it depends on the sheet's curation state. Same for
     * [examplesHtml] (Tatoeba pairs, honoring `removedTatoebaIdx`).
     */
    fun forWord(
        word: String,
        reading: String,
        pos: String,
        definitionHtml: String,
        freqScore: Int,
        imageFilename: String?,
        examplesHtml: String = "",
    ): CardOutputs = CardOutputs(
        expression = word,
        reading = reading,
        sentence = "",
        sentenceTranslation = "",
        picture = pictureHtml(imageFilename),
        definition = definitionHtml,
        examples = examplesHtml,
        frequency = SentenceAnkiHtmlBuilder.starsString(freqScore),
        partOfSpeech = pos,
        wordsTable = "",
        // Flag values for word-mode sends: VOCABULARY_CARD_FLAG fires
        // (Migaku/Lapis vocab-variant signal); sentence flags stay
        // empty since word cards aren't sentence-variant. ALWAYS_ON
        // fires for manually-mapped always-on flag fields.
        vocabularyCardFlag = "x",
        sentenceCardFlag = "",
        targetedSentenceCardFlag = "",
        alwaysOnMarker = "x",
    )

    /**
     * Wraps any highlighted word occurrences in [text] with `<b>…</b>`.
     * Plain text in / plain HTML out — no `<ruby>`, no JavaScript, no
     * bracketed-furigana markup. Templates that want furigana on the
     * Sentence field rely on Anki's `{{furigana:Sentence}}` filter
     * against a separately-mapped bracketed-format field, which is out
     * of scope for v1.
     *
     * Matches against the SURFACE form of each highlighted word, not
     * its dictionary form, so conjugated verbs/adjectives bold
     * correctly. The user looked up 倒れる but the sentence contains
     * 倒れている; we want the latter wrapped. PT's tokeniser already
     * records each word's surface form in [WordEntry.surfaceForm] when
     * the sentence is analysed — we just look it up here and match
     * surfaces literally. Falls back to the dictionary form when
     * surfaceForm is missing (rare; happens for manually-typed words).
     *
     * Longer surfaces are matched first so that "猫" doesn't steal a
     * match from "黒猫" when both are highlighted.
     */
    private fun wrapHighlighted(
        text: String,
        highlighted: Set<String>,
        words: List<SentenceAnkiHtmlBuilder.WordEntry>,
    ): String {
        if (highlighted.isEmpty()) {
            return text.replace(Regex("[\\n\\r]+"), "<br>")
        }
        // Resolve each highlighted dictionary form to its surface form.
        // Multiple WordEntries may share a dictionary form (rare); we
        // collect ALL their surfaces so every occurrence gets bolded.
        // Falls back to the dictionary form itself when no surface was
        // recorded.
        val targets = buildSet {
            highlighted.forEach { dict ->
                if (dict.isEmpty()) return@forEach
                val surfaces = words.asSequence()
                    .filter { it.word == dict && it.surfaceForm.isNotEmpty() }
                    .map { it.surfaceForm }
                    .toList()
                if (surfaces.isEmpty()) {
                    add(dict)
                } else {
                    addAll(surfaces)
                }
            }
        }.toList().sortedByDescending { it.length }

        val sb = StringBuilder()
        var i = 0
        while (i < text.length) {
            val c = text[i]
            if (c == '\n' || c == '\r') {
                sb.append("<br>")
                i++
                while (i < text.length && (text[i] == '\n' || text[i] == '\r')) i++
                continue
            }
            val hit = targets.firstOrNull { text.startsWith(it, i) }
            if (hit != null) {
                sb.append("<b>").append(hit).append("</b>")
                i += hit.length
            } else {
                sb.append(c)
                i++
            }
        }
        return sb.toString()
    }
}
