package com.playtranslate.ui

/**
 * A pluggable "how to render a styling concern on an HTML element"
 * callback. The first param is an optional PlayTranslate CSS class
 * identifier (e.g. `"gl-sense"`, `"gl-hl-bg"`) and the second is any
 * per-callsite inline CSS to also apply.
 *
 * The styler returns a single attribute string ready to inline into an
 * opening tag (e.g. `class="gl-sense" style="margin-top:4px;"` or
 * `style="margin:14px 4px;margin-top:4px;"`). Returning ONE combined
 * attribute string means callsites never accidentally emit two
 * `style=""` attributes on the same element.
 *
 * Usage:
 * ```
 * sb.append("<div ${styler("gl-hl-bg", "margin-bottom:14px;")}>")
 * ```
 */
internal typealias HtmlStyler = (cls: String?, extraInlineStyle: String) -> String

/**
 * Default-model path: emit class refs. The PlayTranslate note types'
 * model CSS ([PtCardTemplates]) supplies the matching `gl-*` rules.
 * Inline styles still pass through.
 */
internal val classStyler: HtmlStyler = { cls, extra ->
    buildString {
        if (cls != null) {
            append("class=\"")
            append(cls)
            append("\"")
            if (extra.isNotEmpty()) append(' ')
        }
        if (extra.isNotEmpty()) {
            append("style=\"")
            append(extra)
            append("\"")
        }
    }
}

/**
 * Structured path: replace known PlayTranslate class refs with inline
 * CSS, merged with any per-callsite inline styles into a single
 * `style=""` attribute. Class refs not in [INLINE_STYLES] pass through
 * as plain `class="cls"` so callers shipping their own classes
 * (e.g. JPMN's `glossary` class) still emit usable markup.
 */
internal val inlineStyler: HtmlStyler = { cls, extra ->
    val inlined = cls?.let { INLINE_STYLES[it] }
    val combined = (inlined.orEmpty()) + extra
    buildString {
        if (cls != null && inlined == null) {
            append("class=\"")
            append(cls)
            append("\"")
            if (combined.isNotEmpty()) append(' ')
        }
        if (combined.isNotEmpty()) {
            append("style=\"")
            append(combined)
            append("\"")
        }
    }
}

/**
 * Escapes HTML metacharacters before interpolating external strings
 * (translation backend output, OCR'd source text, dictionary glosses,
 * user-entered fallback definitions) into Anki card markup. AnkiDroid
 * renders fields in a WebView; without escaping, a `<` arriving from
 * any of those sources can break layout or execute JS in custom note
 * templates.
 *
 * Do NOT call on strings that are HTML by construction — the output of
 * `buildSentencePlain`, `buildSentenceFurigana`,
 * `buildExpressionFurigana`, and `buildWordsHtmlWith` already escapes
 * its inputs and emits safe markup around them.
 */
internal fun htmlEscape(s: String): String {
    if (s.isEmpty()) return s
    val sb = StringBuilder(s.length)
    for (c in s) sb.appendEscaped(c)
    return sb.toString()
}

internal fun StringBuilder.appendEscaped(c: Char): StringBuilder = when (c) {
    '&' -> append("&amp;")
    '<' -> append("&lt;")
    '>' -> append("&gt;")
    '"' -> append("&quot;")
    '\'' -> append("&#39;")
    else -> append(c)
}

/**
 * Wraps an AnkiDroid-side media filename in the `<img>` markup
 * card fields are expected to carry in their Picture/Screenshot slot.
 *
 * Why wrap here and not pass the bare filename: Lapis, JPMN, Migaku,
 * Anki Basic, and PlayTranslate's own note types all render their
 * picture-slot field via a literal `{{Picture}}` (or `{{Screenshot}}`)
 * mustache — they don't wrap the field's contents in `<img>`
 * themselves. The Yomitan ecosystem convention is for the field to
 * ALREADY contain `<img>` markup, typically generated by Yomitan's
 * `{screenshot-html}` marker.
 *
 * `max-width:100%` keeps the image from busting out of narrow card
 * widths on mobile AnkiDroid. We deliberately don't ship
 * border-radius / margins — those are template-styling concerns the
 * owning template's CSS should supply (PlayTranslate's own models do,
 * via `.pt-pic img`).
 */
internal fun pictureHtml(imageFilename: String?): String =
    if (imageFilename.isNullOrEmpty()) ""
    else "<img src=\"${htmlEscape(imageFilename)}\" style=\"max-width:100%;\">"

/**
 * Wraps an AnkiDroid-side media filename in Anki's `[sound:…]` tag.
 *
 * Unlike [pictureHtml] this emits no HTML and does not escape: Anki
 * parses `[sound:filename]` as a directive before HTML rendering, and
 * the filename is one AnkiDroid itself assigned (media-safe). The tag
 * is written verbatim into a field, where AnkiDroid turns it into a
 * play button.
 */
internal fun soundTag(audioFilename: String?): String =
    if (audioFilename.isNullOrEmpty()) "" else "[sound:$audioFilename]"

/**
 * Mode-agnostic inline equivalents of the PlayTranslate model CSS
 * classes. The structured path can't ship
 * `@media(prefers-color-scheme)` adaptive rules without fighting the
 * user's template, so colors are mid-tone values chosen to read on
 * both light and dark AnkiDroid cards. The accent color (#6cd1c2) and
 * highlight (#CC6B1A at 18% alpha) match the model CSS's dark-mode
 * palette closely enough for visual continuity.
 */
internal val INLINE_STYLES: Map<String, String> = mapOf(
    // Per-sense layout
    "gl-sense"     to "margin:14px 4px;",
    "gl-pos"       to "font-size:0.78em;letter-spacing:0.08em;color:#8a8a8a;text-transform:uppercase;",
    "gl-gloss"     to "font-size:1.1em;margin-top:4px;",
    "gl-misc"      to "font-size:0.85em;color:#8a8a8a;font-style:italic;margin-top:2px;",
    "gl-ex"        to "margin:8px 0 0 8px;padding-left:10px;border-left:2px solid #6cd1c2;",
    "gl-ex-tr"     to "font-size:0.92em;color:#8a8a8a;margin-top:2px;",
    "gl-section"   to "font-size:0.78em;letter-spacing:0.08em;color:#8a8a8a;text-transform:uppercase;margin:18px 4px 6px;",
    // Sentence-words HTML
    "gl-secondary" to "color:#8a8a8a;",
    "gl-hint"      to "color:#9a9a9a;",
    "gl-hl"        to "color:#CC6B1A;",
    "gl-hl-bg"     to "background:rgba(204,107,26,0.18);",
)
